apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kb-freshrss
resources:
  - namespace.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - ingress-lan.yaml
  - ingress-lab.yaml
labels:
  - pairs:
      app: kb-freshrss
    includeSelectors: true
