---
apiVersion: v1
kind: Service
metadata:
  name: freshrss
  namespace: kb-freshrss
spec:
  type: ClusterIP
  selector:
    app: freshrss
  ports:
    - name: http
      port: 80
      targetPort: http
